### ISSUE TITLE
Make the script compatible with older versions of pymol

### ISSUE THREAD

**Issue by mjtadema** [mjtadema/garnish#10]
The script is now written for python3 and works in pymol version 2.3.0.
However the most common version is 1.8.x which doesn't work with python 3 (as far as i know).
We should try to make it backwards compatible, if possible.

**Comment by brisvag** [comment]
As far as I can tell, pymol 1.8.x depends on python 2.7.x.

The things that are not compatible with it right now are:
- fstrings: easy to fix with `.format()`
- `shutil.which`: no easy alternative that works cross-platform
- `subprocess.run`: can probably be replaced with `subprocess.Popen`
- `networkx.Graph`: I think `networkx.graph` might just be the old counterpart
- pymol modules: no clue. Need to test properly on an old version of pymol to see

To be honest, backward compatibility all the way back to python2 seems a bit silly :/

**Comment by mjtadema** [comment]
no, agreed, we should just make sure that it works with pymol 1.8.x
It sounds like these problems are very fixable.
shutil.which we can work around, it's not super essential to the main logic.

**Comment by mjtadema** [comment]
we can use [backported fstrings ](https://pypi.org/project/future-fstrings/)

**Comment by brisvag** [comment]
We talked about this and decided to go on with newer python versions. Closed.
